### ISSUE TITLE
Multiple columns on bordered core templates doesn't fit.

### ISSUE THREAD

**Issue by jestonihpi** [GravityPDF/gravity-pdf#1258]
**Description**
Gravity (3) Columns doesn't fit with Zadani and Rubix pdf layout on both RTL and LTR views. 

**Step To Reproduce**
1. Go to 'Forms'
2. Use the core templates Zadani and Rubix.
3. View PDF

**Expected behavior**
Multiple columns length should fit along side with single column.

**Screenshots**
![image](https://user-images.githubusercontent.com/434866/113666594-14c28600-96e2-11eb-83f6-b3b54ae623d5.png)
![image](https://user-images.githubusercontent.com/434866/113666619-1e4bee00-96e2-11eb-83d1-e8ed8aae88b1.png)
![image](https://user-images.githubusercontent.com/434866/113666650-29068300-96e2-11eb-92ea-f026b5f18331.png)
![image](https://user-images.githubusercontent.com/434866/113666688-36237200-96e2-11eb-8c69-3efd01c6fbd8.png)
4 columns.
![image](https://user-images.githubusercontent.com/434866/113666971-b21dba00-96e2-11eb-8c34-7993cc7f3a24.png)

**Comment by jakejackson1** [comment]
@jestonihpi good eyes. I was aware of this issue, but because of the way Gravity Forms is now handling columns (whereby they can be of any width) I haven't currently come up with a way to fix this in a consistent way.

The way CSS Ready Class columns worked prior to 2.5 was that it would always have columns of equal width. We used that limitation to correctly format the columns so that 2/3/4 column variants were always the same width. As you can now create columns with variable width, we cannot use the same method as we previously did. 

The other limitation is how mPDF calculates element widths in relation to margins/padding/borders. Basically, it uses an old browser modal that takes with set width and adds the margin/padding/border width on top of that value. So setting two elements with a 50% width but a margin of 1% would mean the width becomes 52% and the elements are no longer sitting in columns. 

This is something that will require more thought and experimentation to fix (if possible), but since it's a minor formatting issue it's not a blocker for the 6.0 release and I'm going to untag the milestone and the priority tag.
