### ISSUE TITLE
Gravity pdf breaks other mpdf library loading

### ISSUE THREAD

**Issue by abushoaib** [GravityPDF/gravity-pdf#830]
Gravity pdf version 5.0.2 breaks the other Mpdf library calling. We are using mpdf library with custom font and few customization which breaks if we enable gravity pdf because Gravity pdf loads MPDF library globally.  

It needs to load only on gravity pages and  gravity pdf operation so that  it does not break others mpdf library loading. 

https://github.com/GravityPDF/gravity-pdf/blob/development/pdf.php#L143  

 if (GFForms::is_gravity_page() || GFForms::is_gravity_ajax_action()) {
            add_action('plugins_loaded', array($this, 'plugins_loaded'));
  }

**Comment by jakejackson1** [comment]
Unfortunately, merging in that change isn't possible. We actually use to limit when Gravity PDF was loaded but was forced to change this because PDFs can now be generated anywhere on the front end, back end, during AJAX requests, delayed notifications, during REST API requests, via the CRON, or CLI.

I'm in discussions with Kevin about potential work arounds.

**Comment by jakejackson1** [comment]
Hi @abushoaib, I've emailed Kevin a few times about collaborating on a fix to this issue however haven't heard anything back yet. I'd like to get access to your plugin so I can see how mPDF is being loaded and test out various fixes that could be suitable. Is that something you can assist with?
